#pragma once
// Auto-generated by scripts/generate_panel.py -- do not edit manually.
// All coordinates in mm (use mm2px() in VCV widget code).

namespace vortexmm_layout {

constexpr float PANEL_WIDTH  = 71.12f;
constexpr float PANEL_HEIGHT = 128.5f;

// Mode display
constexpr float MODE_DISPLAY_X = 35.56f;
constexpr float MODE_DISPLAY_Y = 16.0f;

// Main knobs
constexpr float CUTOFF_KNOB_X = 35.56f;
constexpr float CUTOFF_KNOB_Y = 28.0f;
constexpr float RESONANCE_KNOB_X = 20.0f;
constexpr float RESONANCE_KNOB_Y = 40.0f;
constexpr float DRIVE_KNOB_X = 51.1f;
constexpr float DRIVE_KNOB_Y = 40.0f;
constexpr float MIX_KNOB_X = 35.56f;
constexpr float MIX_KNOB_Y = 50.0f;

// CV section (jack + attenuverter per row)
// Row order: V/OCT, FM, Resonance, Mode, Drive, Mix
constexpr float CV_VOCT_JACK_X  = 38.0f;
constexpr float CV_VOCT_JACK_Y  = 62.0f;
constexpr float CV_VOCT_ATTEN_X = 50.0f;
constexpr float CV_VOCT_ATTEN_Y = 62.0f;
constexpr float CV_FM_JACK_X  = 38.0f;
constexpr float CV_FM_JACK_Y  = 70.5f;
constexpr float CV_FM_ATTEN_X = 50.0f;
constexpr float CV_FM_ATTEN_Y = 70.5f;
constexpr float CV_RESONANCE_JACK_X  = 38.0f;
constexpr float CV_RESONANCE_JACK_Y  = 79.0f;
constexpr float CV_RESONANCE_ATTEN_X = 50.0f;
constexpr float CV_RESONANCE_ATTEN_Y = 79.0f;
constexpr float CV_MODE_JACK_X  = 38.0f;
constexpr float CV_MODE_JACK_Y  = 87.5f;
constexpr float CV_MODE_ATTEN_X = 50.0f;
constexpr float CV_MODE_ATTEN_Y = 87.5f;
constexpr float CV_DRIVE_JACK_X  = 38.0f;
constexpr float CV_DRIVE_JACK_Y  = 96.0f;
constexpr float CV_DRIVE_ATTEN_X = 50.0f;
constexpr float CV_DRIVE_ATTEN_Y = 96.0f;
constexpr float CV_MIX_JACK_X  = 38.0f;
constexpr float CV_MIX_JACK_Y  = 104.5f;
constexpr float CV_MIX_ATTEN_X = 50.0f;
constexpr float CV_MIX_ATTEN_Y = 104.5f;

// Audio I/O
constexpr float AUDIO_IN_X  = 20.0f;
constexpr float AUDIO_IN_Y  = 116.0f;
constexpr float AUDIO_OUT_X = 51.1f;
constexpr float AUDIO_OUT_Y = 116.0f;

} // namespace vortexmm_layout
