#pragma once
// Generated by scripts/generate_panel_brink.py.
// Coordinates are millimetres for use with mm2px().

namespace brink_layout {

constexpr float PANEL_WIDTH = 60.96f;
constexpr float PANEL_HEIGHT = 128.5f;
constexpr int PANEL_HP = 12;
constexpr float TITLE_Y = 8.0f;
constexpr float LOGO_BASELINE_Y = 124.5f;
constexpr float LOGO_UNDERLINE_Y = 127.0f;
constexpr float POSITION_RAIL_HEIGHT = 10.0f;

constexpr float A_CENTER_KNOB_X = 8.00f;
constexpr float A_CENTER_KNOB_Y = 24.00f;
constexpr float A_WIDTH_KNOB_X = 22.48f;
constexpr float A_WIDTH_KNOB_Y = 24.00f;
constexpr float A_SIGNAL_X = 8.00f;
constexpr float A_SIGNAL_Y = 38.00f;
constexpr float A_POSITION_X = 22.48f;
constexpr float A_POSITION_Y = 38.00f;
constexpr float A_CENTER_CV_X = 8.00f;
constexpr float A_CENTER_CV_Y = 50.00f;
constexpr float A_CENTER_ATTEN_X = 22.48f;
constexpr float A_CENTER_ATTEN_Y = 50.00f;
constexpr float A_WIDTH_CV_X = 8.00f;
constexpr float A_WIDTH_CV_Y = 62.00f;
constexpr float A_WIDTH_ATTEN_X = 22.48f;
constexpr float A_WIDTH_ATTEN_Y = 62.00f;
constexpr float A_INSIDE_X = 8.00f;
constexpr float A_INSIDE_Y = 74.00f;
constexpr float A_OUTSIDE_X = 22.48f;
constexpr float A_OUTSIDE_Y = 74.00f;
constexpr float A_LOW_UP_X = 8.00f;
constexpr float A_LOW_UP_Y = 88.00f;
constexpr float A_HIGH_UP_X = 22.48f;
constexpr float A_HIGH_UP_Y = 88.00f;
constexpr float A_LOW_DOWN_X = 8.00f;
constexpr float A_LOW_DOWN_Y = 100.00f;
constexpr float A_HIGH_DOWN_X = 22.48f;
constexpr float A_HIGH_DOWN_Y = 100.00f;
constexpr float A_POSITION_RAIL_X = 15.24f;
constexpr float A_POSITION_RAIL_Y = 38.00f;
constexpr float B_CENTER_KNOB_X = 38.48f;
constexpr float B_CENTER_KNOB_Y = 24.00f;
constexpr float B_WIDTH_KNOB_X = 52.96f;
constexpr float B_WIDTH_KNOB_Y = 24.00f;
constexpr float B_SIGNAL_X = 38.48f;
constexpr float B_SIGNAL_Y = 38.00f;
constexpr float B_POSITION_X = 52.96f;
constexpr float B_POSITION_Y = 38.00f;
constexpr float B_CENTER_CV_X = 38.48f;
constexpr float B_CENTER_CV_Y = 50.00f;
constexpr float B_CENTER_ATTEN_X = 52.96f;
constexpr float B_CENTER_ATTEN_Y = 50.00f;
constexpr float B_WIDTH_CV_X = 38.48f;
constexpr float B_WIDTH_CV_Y = 62.00f;
constexpr float B_WIDTH_ATTEN_X = 52.96f;
constexpr float B_WIDTH_ATTEN_Y = 62.00f;
constexpr float B_INSIDE_X = 38.48f;
constexpr float B_INSIDE_Y = 74.00f;
constexpr float B_OUTSIDE_X = 52.96f;
constexpr float B_OUTSIDE_Y = 74.00f;
constexpr float B_LOW_UP_X = 38.48f;
constexpr float B_LOW_UP_Y = 88.00f;
constexpr float B_HIGH_UP_X = 52.96f;
constexpr float B_HIGH_UP_Y = 88.00f;
constexpr float B_LOW_DOWN_X = 38.48f;
constexpr float B_LOW_DOWN_Y = 100.00f;
constexpr float B_HIGH_DOWN_X = 52.96f;
constexpr float B_HIGH_DOWN_Y = 100.00f;
constexpr float B_POSITION_RAIL_X = 45.72f;
constexpr float B_POSITION_RAIL_Y = 38.00f;
constexpr float AND_OUTPUT_X = 8.00f;
constexpr float AND_OUTPUT_Y = 114.00f;
constexpr float OR_OUTPUT_X = 23.00f;
constexpr float OR_OUTPUT_Y = 114.00f;
constexpr float XOR_OUTPUT_X = 38.00f;
constexpr float XOR_OUTPUT_Y = 114.00f;
constexpr float STATE_OUTPUT_X = 53.00f;
constexpr float STATE_OUTPUT_Y = 114.00f;

} // namespace brink_layout
