#!/usr/bin/env python3
"""Generate VortexMM panel SVG and C++ coordinate header.

Run from project root:
    python3 scripts/generate_panel.py

Outputs:
    res/VortexMM.svg  - panel SVG background
    src/layout.h      - C++ header with constexpr float coordinates in mm
"""

import os

# Panel dimensions
HP = 14
WIDTH_MM = HP * 5.08   # 71.12mm
HEIGHT_MM = 128.5

# Component sizes (for SVG placeholder circles/rects)
SMALL_KNOB_RADIUS = 2.5
LARGE_KNOB_RADIUS = 4.0
JACK_RADIUS = 3.2
TRIMPOT_RADIUS = 2.0

# Vertical layout
Y_TITLE = 6.5
Y_MODE_DISPLAY = 16.0
Y_CUTOFF_KNOB = 28.0       # large knob, centered
Y_KNOB_ROW1 = 40.0         # Resonance + Drive side by side
Y_KNOB_ROW2 = 50.0         # Mix centered

# CV section: 6 rows
Y_CV_START = 62.0
Y_CV_SPACING = 8.5
# V/OCT=62, FM=70.5, Res=79, Mode=87.5, Drive=96, Mix=104.5

# Audio I/O
Y_AUDIO_IO = 116.0

# Horizontal layout
CENTER_X = WIDTH_MM / 2     # 35.56
LEFT_KNOB_X = 20.0          # Resonance / left knob
RIGHT_KNOB_X = WIDTH_MM - 20.0  # Drive / right knob

# CV section horizontal: label area left, jack center-left, atten center-right
CV_JACK_X = 38.0
CV_ATTEN_X = 50.0

# Audio I/O horizontal
AUDIO_IN_X = 20.0
AUDIO_OUT_X = WIDTH_MM - 20.0


def _circle(x, y, r, fill, stroke):
    return (f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="0.3" />')


def _rect(x, y, w, h, fill, stroke):
    return (f'  <rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="0.3" />')


def generate_svg():
    lines = []
    lines.append(f'<svg xmlns="http://www.w3.org/2000/svg" '
                 f'width="{WIDTH_MM}mm" height="{HEIGHT_MM}mm" '
                 f'viewBox="0 0 {WIDTH_MM} {HEIGHT_MM}">')

    # Background
    lines.append(f'  <rect width="{WIDTH_MM}" height="{HEIGHT_MM}" fill="#1a1a2e" />')

    # Mode display rectangle
    mode_w = WIDTH_MM - 20
    lines.append(f'  <rect x="{CENTER_X - mode_w/2:.1f}" y="{Y_MODE_DISPLAY - 4:.1f}" '
                 f'width="{mode_w:.1f}" height="8" '
                 f'rx="1" fill="#0a0a1a" stroke="#404060" stroke-width="0.3" />')

    # Cutoff knob (large)
    lines.append(_circle(CENTER_X, Y_CUTOFF_KNOB, LARGE_KNOB_RADIUS, '#333', '#aaa'))

    # Resonance + Drive knobs
    lines.append(_circle(LEFT_KNOB_X, Y_KNOB_ROW1, SMALL_KNOB_RADIUS, '#333', '#aaa'))
    lines.append(_circle(RIGHT_KNOB_X, Y_KNOB_ROW1, SMALL_KNOB_RADIUS, '#333', '#aaa'))

    # Mix knob (centered)
    lines.append(_circle(CENTER_X, Y_KNOB_ROW2, SMALL_KNOB_RADIUS, '#333', '#aaa'))

    # CV section: 6 rows of jack + attenuverter
    for i in range(6):
        y = Y_CV_START + i * Y_CV_SPACING
        lines.append(_circle(CV_JACK_X, y, JACK_RADIUS, '#222', '#888'))
        lines.append(_circle(CV_ATTEN_X, y, TRIMPOT_RADIUS, '#333', '#666'))

    # Audio I/O
    lines.append(_circle(AUDIO_IN_X, Y_AUDIO_IO, JACK_RADIUS, '#222', '#888'))
    lines.append(_circle(AUDIO_OUT_X, Y_AUDIO_IO, JACK_RADIUS, '#222', '#888'))

    lines.append('</svg>')
    return '\n'.join(lines)


def generate_coords_header():
    lines = []
    lines.append('#pragma once')
    lines.append('// Auto-generated by scripts/generate_panel.py -- do not edit manually.')
    lines.append('// All coordinates in mm (use mm2px() in VCV widget code).')
    lines.append('')
    lines.append('namespace vortexmm_layout {')
    lines.append('')

    # Panel dimensions
    lines.append(f'constexpr float PANEL_WIDTH  = {WIDTH_MM:.2f}f;')
    lines.append(f'constexpr float PANEL_HEIGHT = {HEIGHT_MM:.1f}f;')
    lines.append('')

    # Mode display
    lines.append('// Mode display')
    lines.append(f'constexpr float MODE_DISPLAY_X = {CENTER_X:.2f}f;')
    lines.append(f'constexpr float MODE_DISPLAY_Y = {Y_MODE_DISPLAY:.1f}f;')
    lines.append('')

    # Main knobs
    lines.append('// Main knobs')
    lines.append(f'constexpr float CUTOFF_KNOB_X = {CENTER_X:.2f}f;')
    lines.append(f'constexpr float CUTOFF_KNOB_Y = {Y_CUTOFF_KNOB:.1f}f;')
    lines.append(f'constexpr float RESONANCE_KNOB_X = {LEFT_KNOB_X:.1f}f;')
    lines.append(f'constexpr float RESONANCE_KNOB_Y = {Y_KNOB_ROW1:.1f}f;')
    lines.append(f'constexpr float DRIVE_KNOB_X = {RIGHT_KNOB_X:.1f}f;')
    lines.append(f'constexpr float DRIVE_KNOB_Y = {Y_KNOB_ROW1:.1f}f;')
    lines.append(f'constexpr float MIX_KNOB_X = {CENTER_X:.2f}f;')
    lines.append(f'constexpr float MIX_KNOB_Y = {Y_KNOB_ROW2:.1f}f;')
    lines.append('')

    # CV section
    lines.append('// CV section (jack + attenuverter per row)')
    lines.append('// Row order: V/OCT, FM, Resonance, Mode, Drive, Mix')
    cv_names = ['VOCT', 'FM', 'RESONANCE', 'MODE', 'DRIVE', 'MIX']
    for i, name in enumerate(cv_names):
        y = Y_CV_START + i * Y_CV_SPACING
        lines.append(f'constexpr float CV_{name}_JACK_X  = {CV_JACK_X:.1f}f;')
        lines.append(f'constexpr float CV_{name}_JACK_Y  = {y:.1f}f;')
        lines.append(f'constexpr float CV_{name}_ATTEN_X = {CV_ATTEN_X:.1f}f;')
        lines.append(f'constexpr float CV_{name}_ATTEN_Y = {y:.1f}f;')
    lines.append('')

    # Audio I/O
    lines.append('// Audio I/O')
    lines.append(f'constexpr float AUDIO_IN_X  = {AUDIO_IN_X:.1f}f;')
    lines.append(f'constexpr float AUDIO_IN_Y  = {Y_AUDIO_IO:.1f}f;')
    lines.append(f'constexpr float AUDIO_OUT_X = {AUDIO_OUT_X:.1f}f;')
    lines.append(f'constexpr float AUDIO_OUT_Y = {Y_AUDIO_IO:.1f}f;')
    lines.append('')

    lines.append('} // namespace vortexmm_layout')
    lines.append('')
    return '\n'.join(lines)


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)

    svg_path = os.path.join(project_dir, 'res', 'VortexMM.svg')
    os.makedirs(os.path.dirname(svg_path), exist_ok=True)
    with open(svg_path, 'w') as f:
        f.write(generate_svg())
    print(f'Wrote {svg_path}')

    header_path = os.path.join(project_dir, 'src', 'VortexMM', 'layout.h')
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, 'w') as f:
        f.write(generate_coords_header())
    print(f'Wrote {header_path}')
