#!/usr/bin/env python3
"""Generate Vortex panel SVG and C++ coordinate header.

Run from project root:
    python3 scripts/generate_panel_vortex.py

Outputs:
    res/Vortex.svg       - panel SVG background
    src/Vortex/layout.h  - C++ header with constexpr float coordinates in mm
"""

import os


# Panel dimensions: Vortex is a compact 6 HP module.
HP = 6
WIDTH_MM = HP * 5.08  # 30.48mm
HEIGHT_MM = 128.5

# Component sizes (for SVG placeholder circles/rects)
KNOB_RADIUS = 3.0
JACK_RADIUS = 3.2           # PJ301MPort (structural guide)
TRIMPOT_RADIUS = 2.0
PIXELS_PER_MM = 15.0 / 5.08
RACK_PORT_RADIUS = 23.7 / (2.0 * PIXELS_PER_MM)
OUTPUT_RING_WIDTH = 0.45
OUTPUT_STROKE_WIDTH = 0.55
OUTPUT_BACKPLATE_RADIUS = RACK_PORT_RADIUS + OUTPUT_RING_WIDTH
OUTPUT_BACKPLATE_FILL = '#39445f'
OUTPUT_BACKPLATE_STROKE = '#dfe7f3'

# The panels carry no decorative screw widgets, so the bottom-centre logo
# can use the same 10 px size as Four and Brink.
LOGO_FONT_SIZE = 10.0

# Vertical layout
Y_MODE_DISPLAY = 16.0
Y_CUTOFF_KNOB = 32.0
Y_CUTOFF_CV = 44.0
Y_RESONANCE_KNOB = 60.0
Y_RESONANCE_CV = 72.0
Y_DRIVE_KNOB = 88.0
Y_DRIVE_CV = 100.0
Y_AUDIO_IO = 115.0

# Horizontal layout
CENTER_X = WIDTH_MM / 2
ATTEN_X = 23.75
AUDIO_IN_X = 9.0
AUDIO_OUT_X = 21.5


def _format_coordinate(value):
    formatted = f'{value:.2f}'
    if '.' in formatted:
        formatted = formatted.rstrip('0')
        if formatted.endswith('.'):
            formatted += '0'
    return formatted


def _circle(x, y, r, fill, stroke, width='0.3'):
    return (f'  <circle cx="{_format_coordinate(x)}" cy="{y:.1f}" r="{r}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{width}" />')


def component_style(name):
    """Return the structural guide style for a named component."""
    if name == 'audio_out':
        return (OUTPUT_BACKPLATE_RADIUS, OUTPUT_BACKPLATE_FILL,
                OUTPUT_BACKPLATE_STROKE, OUTPUT_STROKE_WIDTH)
    if name in ('audio_in', 'cv_jack'):
        return JACK_RADIUS, '#222', '#888', '0.3'
    if name == 'cv_atten':
        return TRIMPOT_RADIUS, '#333', '#666', '0.3'
    return KNOB_RADIUS, '#333', '#aaa', '0.3'


def _append_control(lines, name, x, y):
    radius, fill, stroke, width = component_style(name)
    lines.append(_circle(x, y, radius, fill, stroke, width))


def generate_svg():
    lines = []
    lines.append(f'<svg xmlns="http://www.w3.org/2000/svg" '
                 f'width="{WIDTH_MM}mm" height="{HEIGHT_MM}mm" '
                 f'viewBox="0 0 {WIDTH_MM} {HEIGHT_MM}">')

    # Background
    lines.append(f'  <rect width="{WIDTH_MM}" height="{HEIGHT_MM}" fill="#1a1a2e" />')

    # Mode display
    lines.append('  <!-- Mode display -->')
    mode_width = WIDTH_MM - 10.0
    lines.append(f'  <rect x="{(WIDTH_MM - mode_width) / 2:.1f}" '
                 f'y="{Y_MODE_DISPLAY - 4:.1f}" width="{mode_width:.2f}" '
                 f'height="8" rx="1" fill="#0a0a1a" stroke="#404060" '
                 f'stroke-width="0.3" />')

    # Cutoff group
    lines.append('  <!-- Cutoff knob -->')
    _append_control(lines, 'knob', CENTER_X, Y_CUTOFF_KNOB)
    lines.append('  <!-- Cutoff CV jack + trimpot -->')
    _append_control(lines, 'cv_jack', CENTER_X, Y_CUTOFF_CV)
    _append_control(lines, 'cv_atten', ATTEN_X, Y_CUTOFF_CV)

    # Resonance group
    lines.append('  <!-- Reso knob -->')
    _append_control(lines, 'knob', CENTER_X, Y_RESONANCE_KNOB)
    lines.append('  <!-- Reso CV jack + trimpot -->')
    _append_control(lines, 'cv_jack', CENTER_X, Y_RESONANCE_CV)
    _append_control(lines, 'cv_atten', ATTEN_X, Y_RESONANCE_CV)

    # Drive group
    lines.append('  <!-- Drive knob -->')
    _append_control(lines, 'knob', CENTER_X, Y_DRIVE_KNOB)
    lines.append('  <!-- Drive CV jack + trimpot -->')
    _append_control(lines, 'cv_jack', CENTER_X, Y_DRIVE_CV)
    _append_control(lines, 'cv_atten', ATTEN_X, Y_DRIVE_CV)

    # Audio I/O
    lines.append('  <!-- Audio In -->')
    _append_control(lines, 'audio_in', AUDIO_IN_X, Y_AUDIO_IO)
    lines.append('  <!-- Audio Out -->')
    _append_control(lines, 'audio_out', AUDIO_OUT_X, Y_AUDIO_IO)

    lines.append('</svg>')
    return '\n'.join(lines) + '\n'


def generate_coords_header():
    lines = []
    lines.append('#pragma once')
    lines.append('// Auto-generated by scripts/generate_panel_vortex.py -- do not edit manually.')
    lines.append('// All coordinates in mm (use mm2px() in VCV widget code).')
    lines.append('')
    lines.append('namespace vortex_layout {')
    lines.append('')
    lines.append(f'constexpr float PANEL_WIDTH  = {WIDTH_MM:.2f}f;')
    lines.append(f'constexpr float PANEL_HEIGHT = {HEIGHT_MM:.1f}f;')
    lines.append(f'constexpr float LOGO_FONT_SIZE = {LOGO_FONT_SIZE:.1f}f;')
    lines.append('')

    lines.append('// Mode display (Y matches Four ALGO_DISPLAY_Y)')
    lines.append(f'constexpr float MODE_DISPLAY_X = {CENTER_X:.2f}f;')
    lines.append(f'constexpr float MODE_DISPLAY_Y = {Y_MODE_DISPLAY:.1f}f;')
    lines.append('')

    lines.append('// Centered column X for knobs and CV jacks')
    lines.append(f'constexpr float CENTER_X = {CENTER_X:.2f}f;')
    lines.append('')
    lines.append('// Attenuverter trimpots: 8.5mm right of jack (matches Four CV jack→atten gap)')
    lines.append(f'constexpr float ATTEN_X = {ATTEN_X:.2f}f;')
    lines.append('')

    lines.append('// --- Cutoff group (knob → CV jack + trimpot) ---')
    lines.append('constexpr float CUTOFF_KNOB_X       = CENTER_X;')
    lines.append(f'constexpr float CUTOFF_KNOB_Y       = {Y_CUTOFF_KNOB:.1f}f;')
    lines.append('constexpr float CV_CUTOFF_JACK_X    = CENTER_X;')
    lines.append(f'constexpr float CV_CUTOFF_JACK_Y    = {Y_CUTOFF_CV:.1f}f;')
    lines.append('constexpr float CV_CUTOFF_ATTEN_X   = ATTEN_X;')
    lines.append(f'constexpr float CV_CUTOFF_ATTEN_Y   = {Y_CUTOFF_CV:.1f}f;')
    lines.append('')

    lines.append('// --- Resonance group ---')
    lines.append('constexpr float RESONANCE_KNOB_X       = CENTER_X;')
    lines.append(f'constexpr float RESONANCE_KNOB_Y       = {Y_RESONANCE_KNOB:.1f}f;')
    lines.append('constexpr float CV_RESONANCE_JACK_X    = CENTER_X;')
    lines.append(f'constexpr float CV_RESONANCE_JACK_Y    = {Y_RESONANCE_CV:.1f}f;')
    lines.append('constexpr float CV_RESONANCE_ATTEN_X   = ATTEN_X;')
    lines.append(f'constexpr float CV_RESONANCE_ATTEN_Y   = {Y_RESONANCE_CV:.1f}f;')
    lines.append('')

    lines.append('// --- Drive group ---')
    lines.append('constexpr float DRIVE_KNOB_X       = CENTER_X;')
    lines.append(f'constexpr float DRIVE_KNOB_Y       = {Y_DRIVE_KNOB:.1f}f;')
    lines.append('constexpr float CV_DRIVE_JACK_X    = CENTER_X;')
    lines.append(f'constexpr float CV_DRIVE_JACK_Y    = {Y_DRIVE_CV:.1f}f;')
    lines.append('constexpr float CV_DRIVE_ATTEN_X   = ATTEN_X;')
    lines.append(f'constexpr float CV_DRIVE_ATTEN_Y   = {Y_DRIVE_CV:.1f}f;')
    lines.append('')

    lines.append('// Audio I/O (same height as FB row on Four)')
    lines.append(f'constexpr float AUDIO_IN_X  = {AUDIO_IN_X:.1f}f;')
    lines.append(f'constexpr float AUDIO_IN_Y  = {Y_AUDIO_IO:.1f}f;')
    lines.append(f'constexpr float AUDIO_OUT_X = {AUDIO_OUT_X:.1f}f;')
    lines.append(f'constexpr float AUDIO_OUT_Y = {Y_AUDIO_IO:.1f}f;')
    lines.append('')

    lines.append('} // namespace vortex_layout')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)

    svg_path = os.path.join(project_dir, 'res', 'Vortex.svg')
    os.makedirs(os.path.dirname(svg_path), exist_ok=True)
    with open(svg_path, 'w') as f:
        f.write(generate_svg())
    print(f'Wrote {svg_path}')

    header_path = os.path.join(project_dir, 'src', 'Vortex', 'layout.h')
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, 'w') as f:
        f.write(generate_coords_header())
    print(f'Wrote {header_path}')
