#pragma once
// Auto-generated by scripts/generate_panel_brink_v2.py; do not edit manually.
// All panel coordinates and dimensions are millimetres for use with mm2px().

namespace brink_v2_layout {

constexpr int PANEL_HP = 12;
constexpr float PANEL_WIDTH = 60.96f;
constexpr float PANEL_HEIGHT = 128.5f;
constexpr float TITLE_X = 6.0f;
constexpr float TITLE_Y = 7.0f;
constexpr float TITLE_FONT_SIZE = 6.6f;
constexpr float LOGO_TARGET_X = 42.96f;
constexpr float LOGO_TARGET_Y = 1.8f;
constexpr float LOGO_SCALE = 0.06f;
constexpr float MINIMUM_EDGE_CLEARANCE_MM = 4.0f;
constexpr float MINIMUM_LABEL_CLEARANCE_MM = 0.25f;

// Alternating SEM channel fields and shared logic divider.
constexpr float CHANNEL_A_SECTION_X = 4.0f;
constexpr float CHANNEL_A_SECTION_Y = 12.0f;
constexpr float CHANNEL_A_SECTION_WIDTH = 24.48f;
constexpr float CHANNEL_A_SECTION_HEIGHT = 94.0f;
constexpr float CHANNEL_B_SECTION_X = 32.48f;
constexpr float CHANNEL_B_SECTION_Y = 12.0f;
constexpr float CHANNEL_B_SECTION_WIDTH = 24.48f;
constexpr float CHANNEL_B_SECTION_HEIGHT = 94.0f;
constexpr float LOGIC_DIVIDER_X = 4.0f;
constexpr float LOGIC_DIVIDER_Y = 107.0f;
constexpr float LOGIC_DIVIDER_WIDTH = 52.96f;
constexpr float KNOB_LABEL_OFFSET = 6.3f;
constexpr float PORT_LABEL_OFFSET = 6.35f;
constexpr float EVENT_LABEL_OFFSET = 6.0f;
constexpr float CONTROL_LABEL_FONT_SIZE = 2.35f;
constexpr float PORT_LABEL_FONT_SIZE = 2.15f;
constexpr float EVENT_LABEL_FONT_SIZE = 2.2f;
constexpr float CHANNEL_HEADING_FONT_SIZE = 3.0f;
constexpr float LOGIC_LABEL_FONT_SIZE = 2.15f;

// Read-only window rail bounds.
constexpr float RAIL_WIDTH = 2.0f;
constexpr float POSITION_RAIL_TOP = 21.16023f;
constexpr float POSITION_RAIL_BOTTOM = 67.0132f;
constexpr float POSITION_RAIL_HEIGHT = 45.85297f;
constexpr float Y_POSITION_RAIL = 44.086715f;

// V2 light and marker accents.
constexpr int SECTION_BLUE_GREY_R = 85;
constexpr int SECTION_BLUE_GREY_G = 109;
constexpr int SECTION_BLUE_GREY_B = 128;
constexpr int FUNCTION_ORANGE_R = 183;
constexpr int FUNCTION_ORANGE_G = 105;
constexpr int FUNCTION_ORANGE_B = 60;
constexpr int CHANNEL_A_ACCENT_R = 85;
constexpr int CHANNEL_A_ACCENT_G = 109;
constexpr int CHANNEL_A_ACCENT_B = 128;
constexpr int CHANNEL_B_ACCENT_R = 183;
constexpr int CHANNEL_B_ACCENT_G = 105;
constexpr int CHANNEL_B_ACCENT_B = 60;

constexpr float A_CENTER_KNOB_X = 8.02f;
constexpr float A_CENTER_KNOB_Y = 25.0f;
constexpr float A_WIDTH_KNOB_X = 22.46f;
constexpr float A_WIDTH_KNOB_Y = 25.0f;
constexpr float A_SIGNAL_X = 22.46f;
constexpr float A_SIGNAL_Y = 39.0f;
constexpr float A_POSITION_X = 8.02f;
constexpr float A_POSITION_Y = 39.0f;
constexpr float A_CENTER_CV_X = 22.46f;
constexpr float A_CENTER_CV_Y = 51.0f;
constexpr float A_CENTER_ATTEN_X = 8.02f;
constexpr float A_CENTER_ATTEN_Y = 51.0f;
constexpr float A_WIDTH_CV_X = 22.46f;
constexpr float A_WIDTH_CV_Y = 63.0f;
constexpr float A_WIDTH_ATTEN_X = 8.02f;
constexpr float A_WIDTH_ATTEN_Y = 63.0f;
constexpr float A_INSIDE_X = 8.02f;
constexpr float A_INSIDE_Y = 75.0f;
constexpr float A_OUTSIDE_X = 22.46f;
constexpr float A_OUTSIDE_Y = 75.0f;
constexpr float A_LOW_UP_X = 8.02f;
constexpr float A_LOW_UP_Y = 89.0f;
constexpr float A_HIGH_UP_X = 22.46f;
constexpr float A_HIGH_UP_Y = 89.0f;
constexpr float A_LOW_DOWN_X = 8.02f;
constexpr float A_LOW_DOWN_Y = 101.0f;
constexpr float A_HIGH_DOWN_X = 22.46f;
constexpr float A_HIGH_DOWN_Y = 101.0f;
constexpr float A_POSITION_RAIL_X = 15.24f;
constexpr float A_POSITION_RAIL_Y = 44.086715f;
constexpr float B_CENTER_KNOB_X = 38.5f;
constexpr float B_CENTER_KNOB_Y = 25.0f;
constexpr float B_WIDTH_KNOB_X = 52.94f;
constexpr float B_WIDTH_KNOB_Y = 25.0f;
constexpr float B_SIGNAL_X = 38.5f;
constexpr float B_SIGNAL_Y = 39.0f;
constexpr float B_POSITION_X = 52.94f;
constexpr float B_POSITION_Y = 39.0f;
constexpr float B_CENTER_CV_X = 38.5f;
constexpr float B_CENTER_CV_Y = 51.0f;
constexpr float B_CENTER_ATTEN_X = 52.94f;
constexpr float B_CENTER_ATTEN_Y = 51.0f;
constexpr float B_WIDTH_CV_X = 38.5f;
constexpr float B_WIDTH_CV_Y = 63.0f;
constexpr float B_WIDTH_ATTEN_X = 52.94f;
constexpr float B_WIDTH_ATTEN_Y = 63.0f;
constexpr float B_INSIDE_X = 38.5f;
constexpr float B_INSIDE_Y = 75.0f;
constexpr float B_OUTSIDE_X = 52.94f;
constexpr float B_OUTSIDE_Y = 75.0f;
constexpr float B_LOW_UP_X = 38.5f;
constexpr float B_LOW_UP_Y = 89.0f;
constexpr float B_HIGH_UP_X = 52.94f;
constexpr float B_HIGH_UP_Y = 89.0f;
constexpr float B_LOW_DOWN_X = 38.5f;
constexpr float B_LOW_DOWN_Y = 101.0f;
constexpr float B_HIGH_DOWN_X = 52.94f;
constexpr float B_HIGH_DOWN_Y = 101.0f;
constexpr float B_POSITION_RAIL_X = 45.72f;
constexpr float B_POSITION_RAIL_Y = 44.086715f;
constexpr float AND_OUTPUT_X = 8.02f;
constexpr float AND_OUTPUT_Y = 114.0f;
constexpr float OR_OUTPUT_X = 23.0f;
constexpr float OR_OUTPUT_Y = 114.0f;
constexpr float XOR_OUTPUT_X = 38.0f;
constexpr float XOR_OUTPUT_Y = 114.0f;
constexpr float STATE_OUTPUT_X = 52.94f;
constexpr float STATE_OUTPUT_Y = 114.0f;

} // namespace brink_v2_layout
