#pragma once
// Auto-generated by scripts/generate_panel.py -- do not edit manually.
// All coordinates in mm (use mm2px() in VCV widget code).

namespace fourmm_layout {

constexpr float PANEL_WIDTH  = 132.08f;
constexpr float PANEL_HEIGHT = 128.5f;

// Label positions (for NanoVG rendering)
constexpr float LABEL_COL_X   = 17.0f;
constexpr float OP_HEADER_Y   = 46.0f;

// Global controls
constexpr float ALGO_DISPLAY_X = 66.0f;
constexpr float ALGO_DISPLAY_Y = 15.0f;
constexpr float VOCT_JACK_X = 20.0f;
constexpr float VOCT_JACK_Y = 26.0f;
constexpr float FINE_TUNE_KNOB_X = 66.0f;
constexpr float FINE_TUNE_KNOB_Y = 26.0f;
constexpr float VCA_KNOB_X = 105.1f;
constexpr float VCA_KNOB_Y = 26.0f;
constexpr float MAIN_OUTPUT_X = 114.1f;
constexpr float MAIN_OUTPUT_Y = 26.0f;
constexpr float XM_KNOB_X = 20.0f;
constexpr float XM_KNOB_Y = 36.0f;
constexpr float XM_CV_JACK_X = 29.0f;
constexpr float XM_CV_JACK_Y = 36.0f;
constexpr float XM_CV_ATTEN_X = 37.0f;
constexpr float XM_CV_ATTEN_Y = 36.0f;
constexpr float FM_CV_JACK_X = 105.1f;
constexpr float FM_CV_JACK_Y = 36.0f;
constexpr float FM_CV_ATTEN_X = 114.1f;
constexpr float FM_CV_ATTEN_Y = 36.0f;

// Operator knob positions
// Row index: 0=Coarse, 1=Level, 2=Warp, 3=Fold, 4=FB
constexpr float OP1_KNOB0_X = 25.0f;
constexpr float OP1_KNOB0_Y = 55.0f;
constexpr float OP1_KNOB1_X = 25.0f;
constexpr float OP1_KNOB1_Y = 70.0f;
constexpr float OP1_KNOB2_X = 25.0f;
constexpr float OP1_KNOB2_Y = 85.0f;
constexpr float OP1_KNOB3_X = 25.0f;
constexpr float OP1_KNOB3_Y = 100.0f;
constexpr float OP1_KNOB4_X = 25.0f;
constexpr float OP1_KNOB4_Y = 115.0f;
constexpr float OP2_KNOB0_X = 52.0f;
constexpr float OP2_KNOB0_Y = 55.0f;
constexpr float OP2_KNOB1_X = 52.0f;
constexpr float OP2_KNOB1_Y = 70.0f;
constexpr float OP2_KNOB2_X = 52.0f;
constexpr float OP2_KNOB2_Y = 85.0f;
constexpr float OP2_KNOB3_X = 52.0f;
constexpr float OP2_KNOB3_Y = 100.0f;
constexpr float OP2_KNOB4_X = 52.0f;
constexpr float OP2_KNOB4_Y = 115.0f;
constexpr float OP3_KNOB0_X = 79.0f;
constexpr float OP3_KNOB0_Y = 55.0f;
constexpr float OP3_KNOB1_X = 79.0f;
constexpr float OP3_KNOB1_Y = 70.0f;
constexpr float OP3_KNOB2_X = 79.0f;
constexpr float OP3_KNOB2_Y = 85.0f;
constexpr float OP3_KNOB3_X = 79.0f;
constexpr float OP3_KNOB3_Y = 100.0f;
constexpr float OP3_KNOB4_X = 79.0f;
constexpr float OP3_KNOB4_Y = 115.0f;
constexpr float OP4_KNOB0_X = 106.1f;
constexpr float OP4_KNOB0_Y = 55.0f;
constexpr float OP4_KNOB1_X = 106.1f;
constexpr float OP4_KNOB1_Y = 70.0f;
constexpr float OP4_KNOB2_X = 106.1f;
constexpr float OP4_KNOB2_Y = 85.0f;
constexpr float OP4_KNOB3_X = 106.1f;
constexpr float OP4_KNOB3_Y = 100.0f;
constexpr float OP4_KNOB4_X = 106.1f;
constexpr float OP4_KNOB4_Y = 115.0f;

// Freq-mode toggle positions (row 0, middle sub-column)
constexpr float OP1_TOGGLE_X = 33.5f;
constexpr float OP1_TOGGLE_Y = 55.0f;
constexpr float OP2_TOGGLE_X = 60.5f;
constexpr float OP2_TOGGLE_Y = 55.0f;
constexpr float OP3_TOGGLE_X = 87.5f;
constexpr float OP3_TOGGLE_Y = 55.0f;
constexpr float OP4_TOGGLE_X = 114.6f;
constexpr float OP4_TOGGLE_Y = 55.0f;

// Fine trimpot positions (row 0, right sub-column)
constexpr float OP1_FINE_X = 42.0f;
constexpr float OP1_FINE_Y = 55.0f;
constexpr float OP2_FINE_X = 69.0f;
constexpr float OP2_FINE_Y = 55.0f;
constexpr float OP3_FINE_X = 96.0f;
constexpr float OP3_FINE_Y = 55.0f;
constexpr float OP4_FINE_X = 123.1f;
constexpr float OP4_FINE_Y = 55.0f;

// Operator CV positions (jack + attenuverter beside knob)
// CV index: 0=Level, 1=Warp, 2=Fold, 3=FB
// CV row N is at the same Y as knob row N+1
constexpr float OP1_CV0_JACK_X  = 33.5f;
constexpr float OP1_CV0_JACK_Y  = 70.0f;
constexpr float OP1_CV0_ATTEN_X = 42.0f;
constexpr float OP1_CV0_ATTEN_Y = 70.0f;
constexpr float OP1_CV1_JACK_X  = 33.5f;
constexpr float OP1_CV1_JACK_Y  = 85.0f;
constexpr float OP1_CV1_ATTEN_X = 42.0f;
constexpr float OP1_CV1_ATTEN_Y = 85.0f;
constexpr float OP1_CV2_JACK_X  = 33.5f;
constexpr float OP1_CV2_JACK_Y  = 100.0f;
constexpr float OP1_CV2_ATTEN_X = 42.0f;
constexpr float OP1_CV2_ATTEN_Y = 100.0f;
constexpr float OP1_CV3_JACK_X  = 33.5f;
constexpr float OP1_CV3_JACK_Y  = 115.0f;
constexpr float OP1_CV3_ATTEN_X = 42.0f;
constexpr float OP1_CV3_ATTEN_Y = 115.0f;
constexpr float OP2_CV0_JACK_X  = 60.5f;
constexpr float OP2_CV0_JACK_Y  = 70.0f;
constexpr float OP2_CV0_ATTEN_X = 69.0f;
constexpr float OP2_CV0_ATTEN_Y = 70.0f;
constexpr float OP2_CV1_JACK_X  = 60.5f;
constexpr float OP2_CV1_JACK_Y  = 85.0f;
constexpr float OP2_CV1_ATTEN_X = 69.0f;
constexpr float OP2_CV1_ATTEN_Y = 85.0f;
constexpr float OP2_CV2_JACK_X  = 60.5f;
constexpr float OP2_CV2_JACK_Y  = 100.0f;
constexpr float OP2_CV2_ATTEN_X = 69.0f;
constexpr float OP2_CV2_ATTEN_Y = 100.0f;
constexpr float OP2_CV3_JACK_X  = 60.5f;
constexpr float OP2_CV3_JACK_Y  = 115.0f;
constexpr float OP2_CV3_ATTEN_X = 69.0f;
constexpr float OP2_CV3_ATTEN_Y = 115.0f;
constexpr float OP3_CV0_JACK_X  = 87.5f;
constexpr float OP3_CV0_JACK_Y  = 70.0f;
constexpr float OP3_CV0_ATTEN_X = 96.0f;
constexpr float OP3_CV0_ATTEN_Y = 70.0f;
constexpr float OP3_CV1_JACK_X  = 87.5f;
constexpr float OP3_CV1_JACK_Y  = 85.0f;
constexpr float OP3_CV1_ATTEN_X = 96.0f;
constexpr float OP3_CV1_ATTEN_Y = 85.0f;
constexpr float OP3_CV2_JACK_X  = 87.5f;
constexpr float OP3_CV2_JACK_Y  = 100.0f;
constexpr float OP3_CV2_ATTEN_X = 96.0f;
constexpr float OP3_CV2_ATTEN_Y = 100.0f;
constexpr float OP3_CV3_JACK_X  = 87.5f;
constexpr float OP3_CV3_JACK_Y  = 115.0f;
constexpr float OP3_CV3_ATTEN_X = 96.0f;
constexpr float OP3_CV3_ATTEN_Y = 115.0f;
constexpr float OP4_CV0_JACK_X  = 114.6f;
constexpr float OP4_CV0_JACK_Y  = 70.0f;
constexpr float OP4_CV0_ATTEN_X = 123.1f;
constexpr float OP4_CV0_ATTEN_Y = 70.0f;
constexpr float OP4_CV1_JACK_X  = 114.6f;
constexpr float OP4_CV1_JACK_Y  = 85.0f;
constexpr float OP4_CV1_ATTEN_X = 123.1f;
constexpr float OP4_CV1_ATTEN_Y = 85.0f;
constexpr float OP4_CV2_JACK_X  = 114.6f;
constexpr float OP4_CV2_JACK_Y  = 100.0f;
constexpr float OP4_CV2_ATTEN_X = 123.1f;
constexpr float OP4_CV2_ATTEN_Y = 100.0f;
constexpr float OP4_CV3_JACK_X  = 114.6f;
constexpr float OP4_CV3_JACK_Y  = 115.0f;
constexpr float OP4_CV3_ATTEN_X = 123.1f;
constexpr float OP4_CV3_ATTEN_Y = 115.0f;

// Fold type display positions (below fold knob)
constexpr float OP1_FOLD_TYPE_X = 25.0f;
constexpr float OP1_FOLD_TYPE_Y = 107.0f;
constexpr float OP2_FOLD_TYPE_X = 52.0f;
constexpr float OP2_FOLD_TYPE_Y = 107.0f;
constexpr float OP3_FOLD_TYPE_X = 79.0f;
constexpr float OP3_FOLD_TYPE_Y = 107.0f;
constexpr float OP4_FOLD_TYPE_X = 106.1f;
constexpr float OP4_FOLD_TYPE_Y = 107.0f;

// Middle sub-column X per operator (for OP header centering)
constexpr float OP1_MID_X = 33.5f;
constexpr float OP2_MID_X = 60.5f;
constexpr float OP3_MID_X = 87.5f;
constexpr float OP4_MID_X = 114.6f;

} // namespace fourmm_layout
